Update behave.yml

diff --git a/.github/workflows/behave.yml b/.github/workflows/behave.yml
--- a/.github/workflows/behave.yml
+++ b/.github/workflows/behave.yml
@@ -8,8 +8,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    container: seleniarm/standalone-chromium:latest
-
+    container: selenium/standalone-chrome:latest
     services:
       postgres:
         image: postgres:alpine
@@ -29,7 +28,7 @@ jobs:
 
       - name: Install dependencies
         run: |
-          pip install --upgrade pip pipenv
+          python -m pip install --upgrade pip pipenv
           pipenv install --system --dev
           apt-get update && apt-get install -y procps psmisc
 
@@ -42,7 +41,7 @@ jobs:
       - name: Wait for the service
         run: sleep 10
 
-      - name: Run Behave Tests
+      - name: Run Behave tests
         run: behave
         env:
           BASE_URL: "http://localhost:5000"
@@ -50,7 +49,7 @@ jobs:
 
       - name: Show server logs on failure
         if: failure()
-        run: cat server.log || echo "Server log does not exist."
+        run: cat server.log || echo "Server log not found"
 
       - name: Cleanup
         if: always()
